#!/usr/bin/env ruby

name = ARGV[0].to_i.to_s.rjust(3,'0')

puts "Compiling\n"

result = %x[erl -run compile file #{name} -run init stop -noshell]

puts "Running\n"

result = %x[erl -run #{name} -run init stop -noshell]

puts result
